name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, test
      run: |
        npm install
        npm run pipeline -- --email={{email}} --password={{password}}  
      env:
        CI: true
